Bootstrap: docker
FROM: nvcr.io/nvidia/cuda:10.2-base-ubuntu18.04

%environment
    export XDG_RUNTIME_DIR=
    export PATH="$PATH:/opt/pgi/linux86-64/19.10/bin:/usr/local/bin:/opt/anaconda3/bin:/usr/bin"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" 
    export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib" CPATH="$CPATH:/usr/local/include"
    NVARCH=`uname -s`_`uname -m`; export NVARCH
    NVCOMPILERS=/opt/nvidia/hpc_sdk; export NVCOMPILERS
    MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/20.7/compilers/man; export MANPATH
    PATH=$NVCOMPILERS/$NVARCH/20.7/compilers/bin:$PATH; export PATH
    export PATH=$NVCOMPILERS/$NVARCH/20.7/comm_libs/mpi/bin:$PATH
    export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/20.7/comm_libs/mpi/man

%post
    build_tmp=$(mktemp -d) && cd ${build_tmp}
    apt-get -y update
    DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade 
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
	    m4 vim-nox emacs-nox nano zip \
 	    python3 python3-pip python3-setuptools git-core inotify-tools wget\
	    curl git-lfs \
	    build-essential
    rm -rf /var/lib/apt/cache/* 

    pip3 install --upgrade pip
    pip3 install jupyter netcdf4

### NVIDIA HPC SDK 20.7
    wget https://developer.download.nvidia.com/hpc-sdk/nvhpc_2020_207_Linux_x86_64_cuda_multi.tar.gz
    tar xpzf nvhpc_2020_207_Linux_x86_64_cuda_multi.tar.gz

    nvhpc_2020_207_Linux_x86_64_cuda_multi/install
###

    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/anaconda3 
    rm Miniconda3-latest-Linux-x86_64.sh 
    /opt/anaconda3/bin/conda install -y -q netcdf4

    cd /
    rm -rf ${build_tmp}

%files
    English/ /labs

%runscript
    "$@"

%labels
    AUTHOR mozhgank
