# Copyright (c) 2020 NVIDIA Corporation.  All rights reserved.

Bootstrap: docker
#From: nvcr.io/nvidia/deepstream:5.0-20.07-triton
From: nvcr.io/nvidia/deepstream:6.0.1-triton

%runscript

    "$@"

%post
        #Read https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
        apt-key del 7fa2af80
        apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        
        # NVIDIA nsight-systems-cli-2022.1.1, nsight-compute-2022.1.1
        apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        gnupg \
        wget && \
        wget -qO - https://developer.download.nvidia.com/devtools/repos/ubuntu2004/amd64/nvidia.pub | apt-key add -  &&\
        echo "deb https://developer.download.nvidia.com/devtools/repos/ubuntu2004/amd64/ /" >> /etc/apt/sources.list.d/nsight.list &&\
        apt-get update -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nsight-systems-cli-2022.1.1 nsight-compute-2022.1.1
        
        #Update the repo
        apt-get update
        
        #Install required dependencies
        apt-get install ffmpeg python3-gi python3-dev python3-gst-1.0 -y
        apt-get install unzip
        
        #Install pybind11
        pip3 install pybind11
        pip3 install gdown
        
        #Install jupyter-lab packages
        cd /opt/nvidia/deepstream/deepstream-6.0
        pip3 install jupyterlab
        
        
        cd /opt/nvidia/deepstream/deepstream-6.0/python/source_code/dataset/
        python3 /opt/nvidia/deepstream/deepstream-6.0/python/source_code/dataset/download_dataset.py
        ls -l
        unzip deepstream_dataset.zip 
        
        
        #python binding 
        cd /opt/nvidia/deepstream/deepstream/sources 
        git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git
        
        cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/
        git submodule update --init
        mkdir build
        
        cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/build
        cmake ..  -DPYTHON_MAJOR_VERSION=3 -DPYTHON_MINOR_VERSION=8
        make
        apt install libgirepository1.0-dev libcairo2-dev -y
        pip3 install ./pyds-1.1.1-py3-none-linux_x86_64.whl
        
        cd /opt/nvidia/deepstream/deepstream-6.0
        
        
        
%files

    English/* /opt/nvidia/deepstream/deepstream-6.0

%environment
XDG_RUNTIME_DIR=

%labels

AUTHOR Tosin


