# Copyright (c) 2021 NVIDIA Corporation.  All rights reserved.

Bootstrap: docker
FROM: nvcr.io/hpc/pgi-compilers:ce

%environment
    export XDG_RUNTIME_DIR=

%post


%files
    appName_labs /labs

%runscript
    "$@"

%labels
    AUTHOR 
