#-*- coding:utf-8 -*-

# This file is generated from the AUTHORS file during the installation process.
# Do not edit it as your changes will be overwritten.

__authors__ = [
    u"Naveen Michaud-Agrawal",
    u"Elizabeth J. Denning",
    u"Christian Beckstein (logo)",
    u"Joshua L. Adelman",
    u"Shobhit Agarwal",
    u"Irfan Alibay",
    u"Anshul Angaria",
    u"Luís Pedro Borges Araújo",
    u"Balasubramanian",
    u"Utkarsh Bansal",
    u"Jonathan Barnoud",
    u"Tone Bengtsen",
    u"Alejandro Bernardin",
    u"Ninad Bhat",
    u"Mateusz Bieniek",
    u"Wouter Boomsma",
    u"Jose Borreguero",
    u"Cédric Bouysset",
    u"Bart Bruininks",
    u"Sébastien Buchoux",
    u"Sören von Bülow",
    u"David Caplan",
    u"Yuanyu Chang",
    u"Matthieu Chavent",
    u"Kathleen Clark",
    u"Charlie Cook",
    u"Ruggero Cortini",
    u"Davide Cruz",
    u"Robert Delgado",
    u"John Detlefs",
    u"Xavier Deupi",
    u"Jan Domanski",
    u"David L. Dotson",
    u"Ali Ehlen",
    u"Shujie Fan",
    u"Lennard van der Feltz",
    u"Philip Fowler",
    u"Guillaume Fraux",
    u"William Glass",
    u"Joseph Goose",
    u"Richard J. Gowers",
    u"Lukas Grossar",
    u"Abhinav Gupta",
    u"Akshay Gupta",
    u"Benjamin Hall",
    u"Ameya Harmalkar",
    u"Ivan Hristov",
    u"Eugen Hruska",
    u"Kyle J. Huston",
    u"Siddharth Jain",
    u"Joe Jordan",
    u"Jon Kapla",
    u"Navya Khare",
    u"Andrew William King",
    u"Abhishek A. Kognole",
    u"Max Linke",
    u"Philip Loche",
    u"Jinju Lu",
    u"Hugo MacDermott-Opeskin",
    u"Micaela Matta",
    u"Andrew R. McCluskey",
    u"Robert McGibbon",
    u"Rocco Meli",
    u"Manuel Nuno Melo",
    u"Dominik 'Rathann' Mierzejewski",
    u"Henry Mull",
    u"Morgan L. Nance",
    u"Fiona B. Naughton",
    u"Alex Nesterenko",
    u"Hai Nguyen",
    u"Sang Young Noh",
    u"Daniele Padula",
    u"Nabarun Pal",
    u"Mattia F. Palermo",
    u"Danny Parton",
    u"Shakul Pathak",
    u"Joshua L. Phillips",
    u"Kashish Punjani",
    u"Michael Quevillon",
    u"Vedant Rathore",
    u"Tyler Reddy",
    u"Pedro Reis",
    u"Paul Rigor",
    u"Andrea Rizzi",
    u"Carlos Yanez S.",
    u"Utkarsh Saxena",
    u"Marcello Sega",
    u"Sean L. Seyler",
    u"Faraaz Shah",
    u"Abhishek Shandilya",
    u"Shubham Sharma",
    u"Paul Smith",
    u"Andy Somogyi",
    u"Caio S. Souza",
    u"Shantanu Srivastava",
    u"Lukas Stelzl",
    u"Gorman Stock",
    u"Fenil Suchak",
    u"Ayush Suhane",
    u"Matthijs Tadema",
    u"Joao Miguel Correia Teixeira",
    u"Xiki Tempula",
    u"Matthew W. Thompson",
    u"Hao Tian",
    u"Matteo Tiberti",
    u"Wiep van der Toorn",
    u"Isaac Virshup",
    u"Lily Wang",
    u"Nestor Wendt",
    u"Zhiyi Wu",
    u"Zhuyi Xue",
    u"Juan Eiros Zamora",
    u"Johannes Zeman",
    u"Yibo Zhang",
    u"Yuxuan Zhuang",
    u"Oliver Beckstein"
]
