# Copyright (c) 2020 NVIDIA Corporation.  All rights reserved.

Bootstrap: docker
#From: nvcr.io/nvidia/deepstream:5.0-20.07-triton
#From: nvcr.io/nvidia/deepstream:6.0.1-devel
From: nvcr.io/nvidia/deepstream:6.0.1-triton

%runscript
 
    "$@"

%post

    apt-get -y update
    apt-get -y install ffmpeg python3-gi python3-dev python3-gst-1.0 
    
    cd /opt/nvidia/deepstream/deepstream-6.0
    pip3 install jupyterlab
    
    #python binding
    cd /opt/nvidia/deepstream/deepstream/sources 
    git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git
    cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/
    git submodule update --init
    mkdir build
    cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/build
    cmake ..  -DPYTHON_MAJOR_VERSION=3 -DPYTHON_MINOR_VERSION=8
    make
    apt -y install libgirepository1.0-dev libcairo2-dev 
    pip3 install ./pyds-1.1.1-py3-none-linux_x86_64.whl
    
    cd /opt/nvidia/deepstream/deepstream-6.0

%files

    English/* /opt/nvidia/deepstream/deepstream-6.0/

%environment
XDG_RUNTIME_DIR=

%labels

AUTHOR Tosin
