# Copyright (c) 2023 NVIDIA Corporation.  All rights reserved.

Bootstrap: docker
FROM: nvcr.io/nvidia/tensorflow:23.06-tf2-py3

%environment
%post
    apt-get update -y
    apt-get install -y libsm6 libxext6 libxrender-dev git 
    pip3 install opencv-python gdown
    python3 /workspace/python/source_code/dataset.py
        
%files
    English/* /workspace/

%runscript
    "$@"

%labels
    AUTHOR bharatk
