# Copyright (c) 2021 NVIDIA Corporation.  All rights reserved. 

Bootstrap: docker
FROM: nvcr.io/nvidia/nvhpc:22.3-devel-cuda_multi-ubuntu20.04

%environment
    export XDG_RUNTIME_DIR=
    export PATH="$PATH:/usr/local/bin:/opt/anaconda3/bin:/usr/bin"

%post
    build_tmp=$(mktemp -d) && cd ${build_tmp}

    apt-get -y update
    apt-get -y dist-upgrade 
    DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends \
	    m4 vim-nox emacs-nox nano zip\
 	    python3-pip python3-setuptools git-core inotify-tools \
	    curl git-lfs \
	    build-essential libtbb-dev
    rm -rf /var/lib/apt/cache/* 

    pip3 install --upgrade pip
    pip3 install gdown
    apt-get update -y
    apt-get -y install git nvidia-modprobe
    pip3 install jupyterlab
    pip3 install ipywidgets

    apt-get install --no-install-recommends -y build-essential 

    python3 /labs/nways_MD/English/C/source_code/dataset.py
    python3 /labs/nways_MD/English/Fortran/source_code/dataset.py

    apt-get update -y 
    apt-get install --no-install-recommends -y build-essential

    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/anaconda3 
    rm Miniconda3-latest-Linux-x86_64.sh 
    
    cd /
    rm -rf ${build_tmp}

%files
    nways_labs/ /labs
%runscript
    "$@"

%labels
    AUTHOR mozhgank
