#!/bin/bash
#SBATCH --partition=gpu 
#SBATCH --nodes=1 
#SBATCH --gres=gpu:8 
#SBATCH --ntasks=8
##SBATCH --ntasks-per-node=8

mkdir -p ../../source_code/mpi/output_profiler
profiler_output=../../source_code/mpi/output_profiler

#source ~/nways_multigpu/start_mpi_lustre.sh

mpirun --version
nsys --version

$NSIGHT_HOME/nsys profile --trace=cuda,mpi,nvtx,ucx  --stats=true --nic-metrics=true --force-overwrite true -o $profiler_output/jacobi_memcpy_mpi_report_1n mpirun -np 8 --map-by ppr:4:socket ./jacobi_memcpy_mpi -ny 16384