#!/bin/bash
#SBATCH --partition=gpu 
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --ntasks=4
##SBATCH --ntasks-per-node=4

mkdir -p ../../source_code/mpi/output_profiler
profiler_output=../../source_code/mpi/output_profiler

#source ~/nways_multigpu/start_mpi_lustre.sh

mpirun --version
nsys --version


mpirun -np 4 --map-by ppr:4:socket $NSIGHT_HOME/nsys profile --trace=mpi,cuda,nvtx,ucx --stats=true --nic-metrics=true -o $profiler_output/jacobi_cuda_aware_mpi_report.%q{OMPI_COMM_WORLD_RANK}  --force-overwrite true ./jacobi_cuda_aware_mpi -nx 4096 -ny 8192 -skip_single_gpu


mpirun -np 4 --map-by ppr:4:socket $NSIGHT_HOME/nsys profile --trace=mpi,cuda,nvtx,ucx  --stats=true --nic-metrics=true -o $profiler_output/jacobi_cuda_aware_mpi_report_5k.%q{OMPI_COMM_WORLD_RANK}  --force-overwrite true ./jacobi_cuda_aware_mpi -nx 4096 -ny 8192 -skip_single_gpu -niter 5000