# Copyright (c) 2022 NVIDIA Corporation.  All rights reserved.

Bootstrap: docker
FROM: nvcr.io/nvidia/modulus/modulus:22.09

%environment
%post
    pip3 install gdown
    pip3 install --upgrade nbconvert    
%files
    English/* /workspace/

%runscript
    "$@"

%labels
    AUTHOR aswkumar
