#!/bin/bash
#SBATCH --partition=gpu 
#SBATCH --nodes=2
#SBATCH --gres=gpu:8
#SBATCH --ntasks=16
##SBATCH --ntasks-per-node=8

mkdir -p ../../source_code/nccl/output_profiler
profiler_output=../../source_code/nccl/output_profiler

#source ~/nways_multigpu/start_mpi_lustre.sh

mpirun --version
nsys --version


mpirun -np 16 --map-by ppr:4:socket $NSIGHT_HOME/nsys profile --trace=cuda,mpi,nvtx,ucx  --stats=true --nic-metrics=true --force-overwrite true -o $profiler_output/jacobi_nccl_report_2n.%q{OMPI_COMM_WORLD_RANK} ./jacobi_nccl -ny 32768 -niter 5000 -skip_single_gpu